### ISSUE TITLE
Seeking a frontend Developer for Admin Panel Dev

### ISSUE THREAD

**Issue by Prady96** [fix-the-internet/spring-mvp-lab#13]
We can provide API we are looking for a person who could display graphs using D3 and could do animations in javascript for the website.

Thanks

**Comment by Prady96** [comment]
Please comment if you are interested! or email me at pradyumg@gmail.com. 

We are looking to submit the application by tomorrow.

**Comment by addissemagn** [comment]
Hi @Prady96 , I'm a Computer Engineering student at the University of Toronto with a background in full-stack development and 2 years of experience developing websites and working with Javascript. I'm interested in joining your team and would love to learn more about your idea!

**Comment by addissemagn** [comment]
Hi Pradyum, I'm a Computer Engineering student at the University of Toronto with a background in full-stack development and 2 years of experience developing websites. I've worked with JavaScript and I'm a quick learner. I'm interested in joining your team and would love to learn more about your idea.

**Comment by manukoip** [comment]
Hi @Prady96, I am an Electrical Engineering student at the University of British Columbia. I have done a few projects in Front end domain (HTML/CSS/JavaScript). I am interested to work with you and would love to talk with you about your idea.

**Comment by Ntiyiso-Rikhotso** [comment]
Hi @Prady96 , I am a full stack developer who work with PHP(Laravel, CodeIgniter, Drupal etc), Javascript and its libraries(NodeJs, VueJs, AngualarJs, React, AdonisJs etc, Quasar) and I am interested
