### ISSUE TITLE
A few ideas

### ISSUE THREAD

**Issue by dynamoRando** [fix-the-internet/spring-mvp-lab#20]
Hi everyone -

I have my own project already started but also have other ideas that others are willing to pursue if they need some inspiration. Most of the spirit of these ideas are to drive misinformation or echo chambers away from the internet.

- a browser plugin that helps you better understand if the news article you are reading is "balanced" or if you're missing more details from the story. How do you know you're getting the full story from a news article? What biases may the author or website have? Can we leverage AI to help understand some of this? people today don't trust the media, leading to issues. can we leverage technology to help regain that trust?

- a social networking site that actively works against building echo chambers and dis-information campaigns and trolls. maybe something that required people to post video responses to be more "human"? maybe a news feed that worked to show you views and posts that are counter to your own worldviews? some sort of social networking site that was way more thoughtful at the discussions it was trying to promote and the content it's users were putting out.

- a "penny" internet. too often when browsing the internet I will find a recipe or page that I really like, but the page is just covered in ads. I would love to be able to "pay" the author of that content to remove the ads for some minimal fiscal amount to show that I appreciate that content; while also being able to be ensured that I am genuinely not being tracked by that web page. the main problem with this are transaction fees.

- a database system that gave users ownership of their data. users would cooperative to allow applications to access their data, but could revoke access to their data if they so choose. this would be in a similar spirit to the SOLID project by tim bernes lee.

- for those looking for a Covid-19 related project: south korea used some invasive techniques to try and shame people into social distancing. Is there a way we can respect privacy while at the same time being able to aggregate information to see if a population is adhering to distancing guidelines? Could we then later take that data and overlay with how Covid-19 affected various places?

**Comment by shb9019** [comment]
Hey @dynamoRando, these are some great ideas. For the "penny internet" concept, check out [Brave](https://brave.com/) browser.

**Comment by plastikfan** [comment]
Hi @dynamoRando, you have some good ideas, but it looks like to me that you have not heard much if anything about the Crypto industry. As @shb9019 has suggested, the your penny internet idea is a well trodden in crypto circles. The guy who launched the Brave browser "Brendan Eich", also designed the Javascript language and launched a crypto token: "Basic Attention Token" which is basically your penny internet idea. There are also other crypto project s doing a similar thing, so this is a well worn path. Your idea about a database system that gives users ownership of their data sounds very similar to the "Nuggets" token.
Anyway, good luck with your project, I hope it goes well. I am looking for a project to work on, but will give some of your good ideas some consideration, cheeers.

**Comment by dynamoRando** [comment]
HI @plastikfan -

I appreciate the feedback. And I'm going to probably say something controversial - I honestly dislike anything having to with blockchain based technologies. 

Before everyone flames me to death on this, I want to say that I've looked at blockchain based solutions, and I've come to the conclusion that while there are certain applications for them that fit; they are certainly not a one size fits all.

This company, for example, started up in my town and I still don't know exactly what the actual product is -

https://www.blockchains.com/

I've also looked at very hard this project

https://blockstack.org/

For awhile now, but have found it buggy on my own machine; and there aren't many "d-apps" that worked.

I honestly don't buy into any of these solutions as truly moving the internet forward. I'd love to be educated on why I am wrong. I believe blockchain fits certain use cases, like tracking data on an Internet Of Things based solution, but beyond that I just don't see it moving the internet forward.

Again, I'd love to be convinced otherwise.

**Comment by Blake-Emigro** [comment]
Re: penny internet - https://www.tipalink.com/ and https://www.buymeacoffee.com/
Re: database - I have similar feelings about this and it will be part of my project
Re: blockchain / crypto - I'm with ya bud, I walked away from that once I saw the futility in it all

**Comment by plastikfan** [comment]
> HI @plastikfan -
> 
> I appreciate the feedback. And I'm going to probably say something controversial - I honestly dislike anything having to with blockchain based technologies.
> 
> Before everyone flames me to death on this, I want to say that I've looked at blockchain based solutions, and I've come to the conclusion that while there are certain applications for them that fit; they are certainly not a one size fits all.
> 
> This company, for example, started up in my town and I still don't know exactly what the actual product is -
> 
> https://www.blockchains.com/
> 
> I've also looked at very hard this project
> 
> https://blockstack.org/
> 
> For awhile now, but have found it buggy on my own machine; and there aren't many "d-apps" that worked.
> 
> I honestly don't buy into any of these solutions as truly moving the internet forward. I'd love to be educated on why I am wrong. I believe blockchain fits certain use cases, like tracking data on an Internet Of Things based solution, but beyond that I just don't see it moving the internet forward.
> 
> Again, I'd love to be convinced otherwise.

Well I must admit, there is a lot of hot air in the industry, but that shouldn't put you off the many really good projects that do exist. It's still very early, but I do have faith that the best ones will deliver, its just a matter of time. Some of the biggest projects have had to go through a second iteration and are still going through a rebirth, which is good to see to ensure that what pops out the other end will be useful to all, cheers.

**Comment by dynamoRando** [comment]
@Blake-Emigro - what does your project look like?

**Comment by Blake-Emigro** [comment]
> @Blake-Emigro - what does your project look like?
Build an open-source, privacy-based, decentralized search / browser / CMS / app store on top of @firefox
- specifically for legal. Make a separate source of truth, and a platform for practitioners and #legaltech to serve more people, with a universal login ID & profile. #a2j 

[GLH Projects.docx](https://github.com/fix-the-internet/spring-mvp-lab/files/4423968/GLH.Projects.docx)

**Comment by Blake-Emigro** [comment]
Here's part of what I wrote in the Slack channel. It's kind of a distraction from my existing projects, but it's the infrastructure that my projects and more could sit on top of.

**Comment by dynamoRando** [comment]
Hey all, I'm just not going to do the spring event. Good luck to you all.
