### ISSUE TITLE
Looking for teammates with NLP experience to build a T&C Parser 

### ISSUE THREAD

**Issue by shb9019** [fix-the-internet/spring-mvp-lab#23]
Hey Guys,
    As we all know, the "terms and conditions" pages of almost all sites are way too long to read. I was thinking of building a browser extension that can basically just highlight the most important sentences one needs to be cautious about before signing it. This way, it does not interrupt the user work flow and can know what data is being taken by the website / application. 
   I've got pretty good experience with web development and some experience in NLP and DL.

**Comment by nikhilranjan7** [comment]
Hi, Idea seems interesting. I have previous NLP experience. Can we talk on slack ?

**Comment by AravjitSachdeva** [comment]
Hey! 
I like your idea!
I have experience in NLP, DL, and creating and deploying data pipelines for machine learning solutions which could be essential for the project. Feel free to message me as well. Can we all talk on slack?

**Comment by JING1201** [comment]
Hi! I really like your idea, and I have previous experience with NLP but recently shifted to focus on web apps. How do we join the slack and find each other on slack?

**Comment by shb9019** [comment]
Hey guys! Thanks for showing interest. Please ping me on the builders slack workspace.

**Comment by DanP1925** [comment]
Hello 👋, my name is Daniel Peñaloza. I have been working as an Android developer for a couple of years and currently I'm learning more about backend with ruby on rails. Also, I have previous experience with NLP. I would like to know more about your idea and if possible join your team.

**Comment by ashwin-phadke** [comment]
I've currently started working on summarizing texts using DL in NLP and traditional methods (also working on mozilla deepspeech if that helps). Would love to work with this team. Is there a slack link I can connect with you all to?
