### ISSUE TITLE
Fullstack Developer looking to join a team!

### ISSUE THREAD

**Issue by paridhikhaitan** [fix-the-internet/spring-mvp-lab#24]
Hi, I'm currently a junior and have experience working with a lot of web development projects and also UI/UX Design. I'm interested in working with Misinformation and Collaboration/Society. Let me know if you have any interesting projects!

**Comment by Palmstroemen** [comment]
Hi, would you like to collaborate for a tiny web-based app that helps people to get a feeling for big numbers? Big numbers are everywhere in our news-feeds. 2 Billions here, 1,7 Trillions there. But how much is this? Is it half the GDP of India? Or as much as an aircraft carrier costs? How does this correspond to me as I am maybe an American citizen? So lets divide it by the number of citizens, or the nuber of tax payers, or the number of car drivers, ...

A tiny app that first appears like a calculator with some special keys like (millions, billions, ...)
Once you enter a number that you might have read in the newspaper, you get right into a list of comparable numbers. You might choose from several lists like USA military expenses, World military expenses, Nature (cells in the brain, stars in the universe, ...). Some of these lists will be free, some might be purchasable. This is the "big numbers" part.

But what does this mean to me? I'm part of several communities. My hometown, my state, I'm maybe a retiree or a car driver. So let's divide the big number by the number of these communities. So there is a configurable list of communities characterized by a name and a number to divide. This is the "mean2me" part.

User experience: Enter the big number, swipe to the right: Big Numbers, swipe to the left: mean2me.

I've

**Comment by DanP1925** [comment]
Hello @Palmstroemen 👋, my name is Daniel Peñaloza. I have been working as an Andorid developer for a couple of years and currently I'm learning more about backend with ruby on rails. I would like to know more about your idea and if possible join your team.

**Comment by Palmstroemen** [comment]
Hi!

Thank you for your request.
I had the idea for this app long time ago, also programmed it in Corona which is a cross platform SDK. But never did the final step to bring it into the app stores. Now I want to give it a second try. Maybe just as web-mobile-app.

I’m from Austria.


Here is the idea again:
Hi, would you like to collaborate for a tiny web-based app that helps people to get a feeling for big numbers? Big numbers are everywhere in our news-feeds. 2 Billions here, 1,7 Trillions there. But how much is this? Is it half the GDP of India? Or as much as an aircraft carrier costs? How does this correspond to me as I am maybe an American citizen? So lets divide it by the number of citizens, or the nuber of tax payers, or the number of car drivers, ...

A tiny app that first appears like a calculator with some special keys like (millions, billions, ...)
Once you enter a number that you might have read in the newspaper, you get right into a list of comparable numbers. You might choose from several lists like USA military expenses, World military expenses, Nature (cells in the brain, stars in the universe, ...). Some of these lists will be free, some might be purchasable. This is the "big numbers" part.

But what does this mean to me? I'm part of several communities. My hometown, my state, I'm maybe a retiree or a car driver. So let's divide the big number by the number of these communities. So there is a configurable list of communities characterized by a name and a number to divide. This is the "mean2me" part.

User experience: Enter the big number, swipe to the right: Big Numbers, swipe to the left: mean2me.

I also have a more detailed design document where I have somehow hidden the real purpose of the app.:



Here are some (old) screenshots: (Mrd. Is Billions in German)


Press OK or swipe to the right:

You get a list of items (Events) with some view informations. Your own value is right in the middle of the list. (The blue one) When clicking one item, you get more detailed informations. (There is one HTML-Page behind each item) You can even add an item and contribute your value to the list.


Or swipe to the right: (or maybe a button)

You get also a list but now with configurable communities. In this example:
EU over all inhabitants,
EU tax payers,
My own tax compared to the GDP,
Austria all inhabitants,
Austria tax payers,
German all inhabitants, …. And so on. You can add your own items to this list.

So how to read this. When I read of 1 Billion (1 Mrd.)  in the news and it concerns the EU … that means 1,43 for me. Whatever Number this means. €, $, plastic spoons, mosquitos, …

You get the idea.

I believe such an app would help people to better understand these big numbers we are surrounded all the times.

Hope to read from you.
Best regards,
Oliver

**Comment by amustaque97** [comment]
Hi, l liked the idea and willing to work on this. I'm a full-stack developer with the skillset Good in Django, React and Angular. Let me know if you guys are looking for a team-mate. We can work as a great team and implement this idea.

**Comment by Mutale85** [comment]
Hello @paridhikhaitan 
I have this idea.
Corvid-19 Counselling.
It looks like the effects of covid-19 will also broader mental issues, the loss of business and social status will not stand well with ordinary men.
Create website for psychologists and psychosocial counsellors to help people deal with their anxiety, stress, depression.

Website Functionality

1. Sign Up with email and active phone number.
2. User interface  including live video calls between counsellors and the patients.
3. Live voice calls between the counsellors and the patients.
4. Send an appointment sms with a link to the counsellor and the patient.

email me at mulenga@osabox.com if you are interested in being part f the team.

**Comment by Palmstroemen** [comment]
Hi amustaque97. Definitively. If you like the idea, you are welcome. We can start with a team of 2. So let's do this. Maybe we'll find some more team members later. So let's go. :-))

**Comment by Palmstroemen** [comment]
Hi @Daniel Penaloza. Sorry I didn't respond yesterday. Now the application phase has passed. But to be honest, I believe we will not get in. Nevertheless, I'd like to build this app. If you are still interested, even if we get no funding, then let me know: palmstroem177@gmail.com
