### ISSUE TITLE
Looking for Web Developer (back-end) and Product/User Experience Researchers for a Community Support Web App

### ISSUE THREAD

**Issue by hrishikeshpaul** [fix-the-internet/spring-mvp-lab#25]
Hi, Paul here. I'm a Computer Science graduate student at Indiana University. COVID-19 has been an extremely trying situation for all of us, and as a Computer Scientist, I believe I have the necessary skills to bring about a change. I'm extremely proficient with web development frameworks (full-stack), computer vision and deep learning. You can find more about me on my [Portfolio](https://hrishikeshpaul.github.io/), [LinkedIn](https://www.linkedin.com/in/hrishikeshpaul/) and [Resume](https://drive.google.com/file/d/1EoRMTOOdKzXYsab2dLbCvvikoL1Aoq0U/view). 

My team-mate and I currently in the nascent stages of product ideation, where our fundamental idea is to build a platform wherein, local communities can support one and other by pooling in resources. We also intend to perform exploratory analysis of the gathered data using various NLP/ML models for helping the community. (very abstract, I know)

We're pretty much well versed with web designing, planning, development and management as well as the NLP/AI part of it, which is why we're looking for a back-end developer, specially who knows how to scale applications (dev ops kinda stuff). We're also looking for a Product/User Experience researcher because our application is for the community, and we need someone to properly guide the product by finding loopholes, figuring out what the community wants and making the right design choices. If this sounds interesting to you and you feel you'll fit in  please feel free to message on my slack (@Paul) or drop a comment below! Thank you and stay safe!

**Comment by Mutale85** [comment]
What kind of backend are you looking for? I use php and MySQL for my backend and DB.

**Comment by Ntiyiso-Rikhotso** [comment]
Hi @hrishikeshpaul , I am a fullstack interested in joining your team

**Comment by hrishikeshpaul** [comment]
@Mutale85 hey we're looking for someone who knows system architecture, in order to scale applications (dev-ops). Stuff like Kuberenetes, Jenkins, Docker, NGINX etc.

@Ntiyiso-Rikhotso hey, like the above answer. We are a team of 2 full stack developers, but need someone who could scale our application.

**Comment by Ntiyiso-Rikhotso** [comment]
Can I conclude that you are not looking for a backend? Dev-ops engeener instead however I do have Docker experience 

Reach out to me if you need more information here [Ntiyiso Rikhotso](https://www.linkedin.com/in/ntiyiso-rikhotso/)

**Comment by OceanUX** [comment]
hi @hrishikeshpaul, 
your project looks very interesting,  I'm currently a UX engineering master student at Goldsmiths, I would like to join your team to help you do the user research. You can find more information on about me [Linkedin](www.linkedin.com/in/shaw-rong-tsai-835046143)
