### ISSUE TITLE
Daniel Hong - Looking For Team!

### ISSUE THREAD

**Issue by daniellimhong** [fix-the-internet/spring-mvp-lab#42]
** Name **
Daniel Hong

** Skillset **
React.js, JavaScript, Node/Express, some Postgres & Mongo

** Short Bio **
Hello! My name is Daniel and I'm a junior developer looking to spend my time in quarantine wisely by participating in this program! I have a non-traditional background into code as a bootcamper and since graduating, I've been gaining experience through self-study, personal projects, and internships.  I am looking to use my experience to contribute to a team that will have me! I spend a lot of my time sharpening my React skills and solidifying my JavaScript and some things next on my "learning" list are Typescript, GraphQL, and Ruby and Rails.

** Why Work With Me **
I love what I do and though I'm new to the crowd, every time I get that click, that feeling when something complicated or new begins to make sense, I get that rush of excitement comparable to scoring the game winning shot! As you can see, I'm a sports guy as well and I believe it helped me thrive in a team environment. I'm responsive and dedicated to my craft and committed to improving it. With that said, I'd love to learn more about how I can contribute to your team!

** Location **
Phoenix, AZ (MST/PST)

** University / Work Affiliation **
Arizona State University

** LinkedIn **
linkedin.com/in/daniellimhong

**Comment by tabcat** [comment]
Hey Daniel take a look at my project issue see what u think: https://github.com/fix-the-internet/spring-mvp-lab/issues/45
let me know if you are interested!

**Comment by sanikavedak09** [comment]
Hi Daniel, I am Sanika. UX designer doing masters in Indiana University, USA. I have 2 yrs of experience.

Skills: design thinking, prototyping, wireframing, adobe xd, conceptualization, business innovation etc

We can talk in more details if you want. I am also looking for a team. 
Connect with me on slack -Sanika Vedak
