### ISSUE TITLE
*SEQUITR* -- Crowd-Sourced COVID19 Forum & Debunking [LOOKING FOR Fullstack/Backend/Frontend]

### ISSUE THREAD

**Issue by sngo103** [fix-the-internet/spring-mvp-lab#43]
** Project Name **
SEQUITR: COVID19 information hub and crowd-sourced combat against misinformation. 

** What you're looking for **
I am looking for a full-stack developer and/or someone who has experience creating React web applications.  Basically, any combination that will end up with a full-stack, i.e. 1 frontend dev + 1 backend dev = 1 fullstack dev. :) It would be helpful if they are passionate about my idea, but if not, hopefully I can convince them. 

** Short Project Description **
tl;dr: crowd-sourced forum & downvoting hoaxes, live updates from CDC,; similar to Quora, but better and specifically for COVID19

The basis of Sequitr is to create a single place for establishing truthful information from trusted institutions and the power of crowdsourcing. One of the biggest problems during the COVID19 pandemic is misinformation. Misleading information about fake “cures” spread like wildfire and creates a false sense of security that leads to reckless behavior. Currently, people are looking to the CDC and the news for answers to their questions, but the CDC can’t answer all their questions and the news can be biased or inaccurate. People are forced to turn to social media to address their fears. Sequitr provides a solution to these problems by creating a place where users can find the most up to date information and ask questions about the pandemic. The three main features of Sequitr are a CDC news feed/resource hub, forum for questions, and polling for identifying hoaxes. The forum and the polling will be done through crowdsourcing. The forum will allow users to post questions and answer questions. This feature is similar to Quora’s product, but Quora is too general and expansive, making it a second thought when faced with COVID19 questions. Sequitr provides a place solely for questions relating to the pandemic. Polling allows users to post images and descriptions of pieces of COVID19 information that seem too good to be true and others can vote for “FACT” or “HOAX” in addition to commenting with an explanation. The MVP for 8 weeks will be a web app with a basic version of these three features and the user account system to facilitate. It will have a feed linked to updates from the CDC about COVID19, possibly from scraping the CDC site or their newsletters. The forum will allow users to post questions and answers. The polling will allow users to post images/descriptions, vote, and comment. These two features will likely be made with Web Sockets. In the future, I hope to create user labels for trusted users, such as infectious disease experts, doctors, and nurses, who would have more weight with their votes and lend credibility, connect volunteers to those in need, strengthen the user security system, and make Sequitr portable enough to be used easily in other countries. The COVID19 crisis has created a vortex of information, often repeated several times throughout the day and people have no easy way of knowing what to trust and how to deal with all the information. Sequitr will be the place they turn to and provide some certainty in these uncertain times.

** Team Bios **
Samantha Ngo - Samantha is currently a computer science undergraduate sophomore at Hunter College in NYC. In the past, Samantha interned as a web developer building a tournament platform website, as a blockchain researcher building a Python price oracle that handles computations on large sets of data, and as a software developer building the foundation of an internal Python mailparser that collects contact information for relationship management. She has had experience working with Python, C++, Javascript(React, Node, MongoDB), Java, Figma, and Git, as well as some lesser-known languages. She is passionate about software engineering, but is looking into going into product design, where she can turn her ideas into a reality. This summer, she is looking forward to her software engineering internship at Paypal.

** Why Work With Us **
Because we're passionate about fighting misinformation in the COVID19 Pandemic.

**Comment by Sangha05** [comment]
Hi @sngo103, I have a similar idea. I plan to train a machine learning algorithm after we have labeled data (which is obtained via crowdsourcing) to check for media bias or misinformation of the article/source. By doing this, new articles can be automatically tagged as "FACT" or "HOAX" when there are not enough upvotes or downvotes that post or they're equal (Keeping in mind the public can also be misinformed). Also, it will help create a media tracker in case the website has more sources added other than CDC in the future. Let us connect if you're interested in adding the ML component to your product. https://mozillabuilders.slack.com/archives/C010KM8KTMX/p1586015669352500
www.linkedin.com/in/sanghamesh-vastrad

**Comment by MaxCo41** [comment]
Hi @sngo103
I'm a young passionate ambitious web developer junior fullstack JS come from Belgium.
I already work on a project in Brussels to help eradicate Covid-19 find donors and make a fundraising website to help hospital and fight this virus.
I really want to take part of this project.

Checkout my Linkedin profile & Github account to know more about my profile :
https://www.linkedin.com/in/maximecollin41/?locale=en_US
https://github.com/MaxCo41

Take care of you and your family

**Comment by MarquiseRosier** [comment]
I love this idea! I'd be totally down to join if you'd allow me. I have some experience as a backend developer/machine learning enthusiast? Some insight on me, I've interned as a ML engineer at Walt Disney got hired to work remotely while I was in college, I worked on a machine learning platform! So I have a little bit of knowledge on AWS, Docker, Serverless, Data Science, if you have a need for any of these skills let's talk :)

**Comment by MCharming98** [comment]
Hey @sngo103 , nice to meet you! My name is Chen Meng and I'm a third-year computer science major student at UC San Diego. I really like your idea of this platform.
In terms of skills and experiences, I have decent front-end programming experience(HTML, CSS, javascript, REST), and backend experience(PostgresSQL, JDBC, Google cloud, Java servlet). I also have a solid mobile development experience(Android) if it is relevant.
I have experience in building a java web application on maven and deploying it on the Google app engine. While we don't have to follow this particular flow, here is one way to do it and I'm open to learning other ways(like Django, I also know python).
Feel free to connect with me on LinkedIn and let me know if you have any questions! Super looking forward to joining your team!
Best,
Chen

https://www.linkedin.com/in/chenmeng98/

**Comment by abhimanyu891998** [comment]
Hi @sngo103! Looks like a great problem to solve during such challenging times. I am Abhi, a final-year computer science student from The University of Hong Kong. I am really interested in working on this project. I can help with full-stack development and have had experience with web and mobile app development through multiple internships and projects in the past.
Have a look at my profiles to know more:
Github: [](https://github.com/abhimanyu891998)
Linkedin: [](https://www.linkedin.com/in/abhimanyue-singh-tanwar-30a424130/)
