### ISSUE TITLE
Yash Handa - LOOKING FOR TEAM

### ISSUE THREAD

**Issue by Yash-Handa** [fix-the-internet/spring-mvp-lab#44]
**Name**
Yash Handa

**Skill Set**

- Front-End: React, Angular
- Back-End: Node(express.js/ hapi.js), Python(Django / Flask)
- API Architecture: REST API, GraphQL API
- Dev-Ops: Docker, Kubernetes
- Database: MongoDB, PostgreSQL
- Algorithms: Graphs, Trees, etc

Have also build projects using these technologies/ skills

**Short Bio**
Hi all, I am a senior year undergraduate (Information Technology) proficient in full-stack and open source technologies. I have been contributing to other projects in the past like node.js, gatsby.js, GraphQl Foundation and Arch eco-system. Other than that I love to draw(sketching/portrait) and do gymming (or any other physical routine).

**Why Work With Me**
You and your team will have a great time working with me as I am a self-motivated and focused individual. I also have some experience working with remote teams in open source projects. Most importantly **I am willing to learning new technologies** (that too fast :-) )

**Location**
Delhi, India

**University**
GGSIPU, Delhi, India

**LinkedIn**
https://www.linkedin.com/in/yash-handa-bb767b130 (lets connect ;-) )

**Comment by tabcat** [comment]
Hey Yash Handa, take a look at my project issue: https://github.com/fix-the-internet/spring-mvp-lab/issues/45
if you have interest feel free to leave a comment or reach out!

**Comment by kul1010** [comment]
Hi Yash,
You have any Idea to develop Application?
What type Application you will develop.
Because till now I didn't get any team. And no more time available to develop Application. Kindly think about any innovative ideas.
