### ISSUE TITLE
Looking for Teammates -- [ IPFS ] File Sync or Secure Messenger

### ISSUE THREAD

**Issue by tabcat** [fix-the-internet/spring-mvp-lab#45]
_If you would like to talk more you can email me (displayed on my profile) or leave a comment.
I will keep this updated as things develop._

**Project Name**
Any ideas? Let's chat!

**Short Project Description**
The project will be a static website and PWA built in React/Redux. There is no backend, all app functionality is done with [js-ipfs](https://github.com/ipfs/js-ipfs) and [orbitdb](https://github.com/orbitdb/orbit-db) instances running in the browser and the app's static website files can be hosted over ipfs by users.

App ideas: a file store that can be replicated and updated across browsers, a secure messaging app useful for resisting large, well-funded, and sophisticated actors (  in theory :P  )

**What you're looking for**
front-end engineer that likes to make beautifully usable interfaces.
software engineer with some experience writing javascript.
don't fit? reach out if you are interested/have some thoughts anyway!

**Team Bios**
Myself: self-taught with 2 years experience, very familiar with ipfs and active contributer to orbitdb

**Why Work With Us**
Build something open source and fun! Learn about what makes IPFS cool. Unique web app architecture?

**Comment by Taiwrash** [comment]
Hi, I am frontend developer and I am very interested in working with you.
Check my GitHub repo below.
https://github.com/Taiwrash

**Comment by Taiwrash** [comment]
Contact me on email: rasheedrtm1@gmail.com

**Comment by Yash-Handa** [comment]
Hi @tabcat,
I realy liked your idea of using IPFS as the foundation of a chatting app with all user-data and messages remaining on the users system only (no big company server scanning over our messages). I would really like to be a part of this project and help forward your vision.

Key interesting points to me:

1. I was recently studding about PWAs and their implications, this project will help me a lot.

2. I could put my react, redux knowledge to use.

3. Will get to learn about IPFS and stuff : )


Key concerns:

1. Synchronisation of user data in different browsers/ computers

2. Security issues with having local data on publically available computers (like library or University computers).
_Suggestion: could use encrypted data. _


If you think I can help, I would be glad to be a part of this project. Could further our discussion in comments, slack or mail (provide info and I will catch up).  :-)

**Comment by tabcat** [comment]
I've sent out an email to everyone who has expressed interest thus far. Check it out! :P

**Comment by Chrysanthus** [comment]
@tabcat Anders. Thank you for inviting me. You have read my qualifications. I have accepted to join your team. Do not forget to read "https://medium.com/mozilla-builders/make-it-real-how-to-make-your-application-for-mozillas-mvp-lab-stronger-c7e07643467c" before applying on our behalves. Do not forget that application deadline is Monday, April 6th, 11:59PM ET. I believe it is the team leader, you alone, that applies.

I have good knowledge in OrbitDB (IPFS, IPFS Pubsub, CRDTs). Hope our application is granted. Let me know if there is anything else, I have to do before the application.

Regards,
Chrysanthus

**Comment by tabcat** [comment]
Greetings @Chrysanthus,
The team is now filled. I can connect you with other people that were interested as well since our projects were somewhat similar.

**Comment by Ntiyiso-Rikhotso** [comment]
Hi @tabcat  , I am interested in your idea and would like to join your team

Please have a look at my profile [Ntiyiso Rikhotso](https://www.linkedin.com/in/ntiyiso-rikhotso/)

**Comment by tabcat** [comment]
Hi @Ntiyiso-Rikhotso, the team has reached max capacity at 4/4 now. Best of luck joining a team, I hope you are able to find one!

**Comment by kul1010** [comment]
Namaste,
I am a MERN DEVELOPER, and interested to work with ReactJs, Redux. Also having skills with PHP, MySQL, MongoDB. And also can design DB. I am interested to work with your team.

**Comment by tabcat** [comment]
Hello @kul1010 the team has reached max capacity at 4/4

**Comment by Ntiyiso-Rikhotso** [comment]
Hi @kul1010 , please email me here truminnd@gmail.com, I am forming a team
