### ISSUE TITLE
Verity Legal Platform -- Looking for: Back-end Web Dev

### ISSUE THREAD

**Issue by Blake-Emigro** [fix-the-internet/spring-mvp-lab#55]
**Project Name**
Verity Legal Platform

**What you're looking for** 
Back-end Web dev (in the Americas)

**Short Project Description** 
Covering these areas: Collaboration & Society, Decentralized Web, Messaging, Misinformation & Content, Surveillance Capitalism

To address the "access to justice gap" globally new collaborative, yet private, systems must be built to serve more people. Consumers need a portal to go to that they can trust, where the legal service providers are authorized, and the legal software products are vetted. Lawyers must have a platform to productize and scale their service delivery, and legaltech companies need a platform to get access to more consumers, while protecting and not selling their data.

The proposal is to fork Firefox and introduce an open-source, decentralized, privacy-based platform that is a search engine & browser for consumers, a site hosting & content management system for lawyers, and a legaltech app store. Make a separate source of truth, away from the fake news and scammers, and a platform for authorized practitioners and vetted legaltech companies to serve more people, with permissioned, universal login IDs & profiles.

Obviously, the roadmap for this project far exceeds the limits of the Mozilla MVP Lab initiative, and the objective is to pick and build the MVP, with the intention of creating a non-profit organization to continue building, with the support of Mozilla and others.

**Team Bios** 
_Blake Sieders_ - Vancouver, Canada - Mechanical Engineering Technologist, Project Manager, former Canadian Immigration Consultant, Tech Founder - 20 years as a professional in the manufacturing industry, and 5 years as a consultant and entrepreneur - shipped one software product and one beta in 2017. Learning to code, (very slowly). 
https://www.linkedin.com/in/blake-sieders/

_Silvia Bon_ - Vancouver, Canada - Brazilian immigrant - Junior Web Dev, Analyst, IT Technician - more than a decade of experience as an technician and analyst, and 1 year as a web developer.
https://www.linkedin.com/in/silviabon/

_Arun Daniel_ - Cincinnati, USA - Indian immigrant - Software Architect, Systems Engineer, Tech Founder - more than a decade of professional experience in systems and software solutions.
https://www.linkedin.com/in/danielarun/

_Rodrigo Wladyka_ - Curitiba, Brazil - Software Engineer - 8 years of experience as a software engineer and architect.
https://www.linkedin.com/in/rodrigo-wladyka/

** Why Work With Us **

- A diverse team of (30+ / 40+) professionals
- Experience building and shipping products
- Experience in legal services delivery
- Maximum 4-hour time difference for team members
- Access to potential customers in US and CA
- Access to overseas markets
- Access to additional team members post-MVP Lab
- Building legaltech products to use on the platform in parallel to MVP Lab
- Because we're nice people?

UPDATE: THE TEAM IS COMPLETE!

**Comment by rwladyka** [comment]
Hello, I'm Rodrigo Wladyka from Curitiba/PR Brazil. I'm front-end developer working with ReactJS make components to e-commerce, but I too have experience with Javascript Vanilla, Java, PHP and a little bit with NodeJS. In Databases I work with PostgreSQL, Oracle and MySQL. I haven't much experience with NoSQL databases, but understand the concept. I think can help you. My linkedin is https://www.linkedin.com/in/rodrigo-wladyka/

**Comment by Blake-Emigro** [comment]
Ola Rodrigo! Thanks for your message. I'm going to connect with you on LinkedIn and then we can chat. Silvia is from Curitiba, and I've been there!
