### ISSUE TITLE
Crowd-sourced Media Bias Tracker -- [LOOKING FOR Full Stack Developer]

### ISSUE THREAD

**Issue by Sangha05** [fix-the-internet/spring-mvp-lab#56]
**Project Name**
Crowd-sourced Media Bias Tracker

**Short Project Description**
There is no agreed-upon methodology or source of quantifying media bias. We'll try tackling this problem through content-based crowd-sourcing: 
1. Popular media websites will be scraped on a daily or hourly basis. 
2. We pass it through a classifier that classifies it as news or opinion, political or not, topics within the political landscape, etc (Crowdsourcing for labeled data). 
3. Anonymize the article and present it to users who'll read it on our website and rate it to be democratic leaning, republic leaning, etc. 
4. We'll use the crowdsourced results from step 3 to quantify, display and track media bias. 

End product: Users can use our website to read articles without having their own bias about media houses and anyone can how the media bias changes for different issues in real-time.

**What you're looking for**
Data Engineer with web scraping expertise for step 1.
NLP Engineer (ideally help with backend as well) for steps 2&3.
Full-Stack Developer for Steps 3&4.

**Team Bios**
www.linkedin.com/in/sanghamesh-vastrad
- Eager to get feedback on the idea and discuss potential roadblocks like ethics/privacy.
- Happy to collaborate or merge the project with anyone who has similar ideas. My expertise lies in machine learning and computational social science.

**Comment by THEMrinaal** [comment]
Hi Sangha,
I am interested in this project! Would love to discuss more about the scope of this project!

**Comment by Sangha05** [comment]
Hi @THEMrinaal, please ping me on Slack @Sanghamesh Vastrad and we can discuss the details!

**Comment by MaxCo41** [comment]
Hi @Sangha05 ,
I'm a young passionate and ambitious web developer Fullstack JS.
I think you idea is great I really want to take part in this project as Fullstack developer for the step 3&4.
You may check my Linkedin account to know more about my profile : 
https://www.linkedin.com/in/maximecollin41/?locale=en_US

**Comment by Sangha05** [comment]
Hi @MaxCo41, I've pinged with you on Slack.
