### ISSUE TITLE
Safe Space -- Looking for an ML developer and a backend developer

### ISSUE THREAD

**Issue by adisen** [fix-the-internet/spring-mvp-lab#57]
###  What you're looking for 
We are looking for an ML engineer and a Backend engineer who has experience working with Bots

### Short Project Description
We all know the rate at which we have fake news and alerts on our social media platforms. And the spread of wrong information is not more apparent than during this crisis. So we want to create a WhatsApp Bot that allows people to verify news and messages that they want to verify. They can also send a message to the Bot to report a piece of news as bad news.

### Team Bios
We are currently two in the team. I am a full-stack JavaScript developer with an interest in ML and AI and the second team member is a UI/UX designer

###  Why Work With Us 
You get to work on a project that is relevant and will be relevant as long as misinformation exists

**Comment by MarquiseRosier** [comment]
Hello! Need a backend developer/machine learning enthusiast? Some insight on me, I've interned as a ML engineer at Walt Disney got hired to work remotely while I was in college, I worked on a machine learning platform! So I have a little bit of knowledge on AWS, Docker, Serverless, Data Science, if you have a need for any of these skills let's talk :)

**Comment by adisen** [comment]
Hi @MarquiseRosier will you be interested in joining the team?

**Comment by THEMrinaal** [comment]
HI @MarquiseRosier , I am interested in working  on this project! My interests and expertise lies in ML, NLP and recently I am working on cloud computing related projects!

**Comment by ashwin-phadke** [comment]
Do take a look at Issue #49 to know about me and let me know if the skillset matches.

**Comment by adisen** [comment]
@ashwin-phadke I like what I see can we talk?

**Comment by adisen** [comment]
@THEMrinaal do you have a public profile that I can check?

**Comment by ashwin-phadke** [comment]
You can check my profile from the issue that I've mentioned using the linked in link or in general visit [website](https://ashwin-phadke.github.io) for the full profile.

**Comment by Pihu1998** [comment]
Hi @adisen . I have some experience working with Bots as I am currently contributing to an Open Source project named "MapBot" which is a Bot related to Google Maps under GSSoC'20 (GirlScript Summer of Code 2020). Also, since I am an Intel Ege AI Scholar and Bertelsmann Technology Scholar in AI Track 2019 offered by Udacity, so I have a fair experience in building a number of projects related to Deep Learning. Am I eligible to join your team?

**Comment by adisen** [comment]
Do you have a public profile?

**Comment by Pihu1998** [comment]
Yes, I do have a public profile @adisen .  This is my [https://www.linkedin.com/in/pranamika-pandey-7a3610171/](LinkedIn Profile) and this is my [https://github.com/Pihu1998](GitHub Profile).
