### ISSUE TITLE
Uncentral -- Looking for team members

### ISSUE THREAD

**Issue by martinheidegger** [fix-the-internet/spring-mvp-lab#65]
**Project Name**: Uncentral

**Looking for**

- A better name
- (Node) Js developer (okay with TypeScript)
- UI designer

**Short Project Description**

Uncentral is the showcase for a decentral document sharing framework that works on mobile app, in react-native and web app. A mobile app will allow to take pictures, modify them and share them under a did. Any change of the document will create a fork. 

<img src="https://user-images.githubusercontent.com/914122/78501277-fc015680-7795-11ea-8cf2-2bdbe1e3ad09.jpg" width="80%" />

Both the mobile phone and the browser have the option to add documents from did's but in the desktop app we can also create artboards.

<img src="https://user-images.githubusercontent.com/914122/78505221-f400e100-77ac-11ea-81f2-6eaf398ffeea.jpg" width="80%" />

The artboards allow a placement of other documents _(using the did's)_ and the artboards will become new did's to share.

<img src="https://user-images.githubusercontent.com/914122/78505266-52c65a80-77ad-11ea-9b72-87e7e03fa191.jpg" width="80%" />

We also want to prepare a did-server that can be started to host the documents and share the documents when the other devices are offline.

<img src="https://user-images.githubusercontent.com/914122/78505164-8fde1d00-77ac-11ea-9c4d-3719ed6d8f8c.jpg" width="80%" />

Depending on our progress we may go into a more creative territory with the artboard.
We plan to build our things on the dat platform and have quite a bit of experience in that space.

**Team Bios**

- [Martin](https://github.com/martinheidegger): Long time JavaScript developer, with decentralization background living in Japan
- [Calm](https://github.com/calm_rad): React Native developer with experience in decentralization, living in the United States. 

**Why Work With Us**

We are experienced with the given tool-set and active in the dat community. We think you can learn a lot about the decentralized work with us and you will build up skills that allow you to create decentralized applications with a broad variety for use cases in future.

**Comment by marcchataigner** [comment]
I like the drawings a lot  :-)    👍

**Comment by marcchataigner** [comment]
Idea sounds fun. Would it work with different "dribble" like www.dribbble.com?  Like every new modification is a dribble.

**Comment by marcchataigner** [comment]
Maybe one question: how to export?  (if it is possible)

**Comment by martinheidegger** [comment]
All artwork gets a link that can be shared between devices (you have the link & the device is online you can access it). We can easily add a download button to download the raw asset.

**Comment by tosfan4ever** [comment]
Hey @martinheidegger, are you still looking for a UX/UI Designer? Because I am one.

**Comment by martinheidegger** [comment]
@tosfan4ever Yes, I am still in the chat (mentioned above), let's have a talk!

**Comment by cmbrydges** [comment]
@martinheidegger Also a UX/UI Designer & Researcher looking for a team

My work here: www.christinebrydges.com

Let me know if you'd like to connect!

**Comment by martinheidegger** [comment]
→ https://meet.jit.si/uncentral-mozilla-first-call

**Comment by martinheidegger** [comment]
We found members to help, thank you for your interest.
