### ISSUE TITLE
82ba10b5e8dc - [LOOKING FOR TEAM]

### ISSUE THREAD

**Issue by 82ba10b5e8dc** [fix-the-internet/spring-mvp-lab#69]
** Name **
82ba10b5e8dc

** Skillset **
JavaScript, TypeScript, Python, React, Redux, Express, Django

** Short Bio **
I'm a full-stack developer from a design background with 8 years of experience building web applications. I want to help build tools that give people the ability to create social, environmental and economic change.

** Why Work With Me **
I am a self-starter and love to create things pragmatically. I like ensuring there is good open communication and creating concise requirements so we build the right thing in a reasonable amount of time.

** Location **
America/Los_Angeles

** University / Work Affiliation **
N/A

** LinkedIn **
N/A

You can see my other online profiles:
https://stackoverflow.com/users/2121538/3066d0
https://medium.com/@console.blog

**Comment by martinheidegger** [comment]
Hello @82ba10b5e8dc - how about #65 ? Give me a call (needs to be soon! Deadline in 3 hrs) - https://keybase.io/martinheidegger or at martin@consento.org
