### ISSUE TITLE
Looking for another teammate with Experience in design for mobile applications or mobile engineering in general. 

### ISSUE THREAD

**Issue by atearjen** [fix-the-internet/spring-mvp-lab#7]
Hello, 

Our team is helping bridge the gap between personal trainers and clients to ensure the mental health of all people is maintained and to prevent body dysmorphia during this time because clients are not able to go to the gym. 

We currently have an Android, IOS, and an inexperienced Designer and are looking for one more to add to our team. We need the most help with design, but if you know android or IOS that would be good too. 

Please comment if you are interested! or email me at amtearjen@ucdavis.edu. We are looking to submit the application by tomorrow. Thanks! 

Allison

**Comment by ShaswatJBabhulgaonkar** [comment]
Hello Allison !!!
This is Shaswat here. I've sent you my details. Please check your email and let me know.

**Comment by richard457** [comment]
@ShaswatJBabhulgaonkar Would you mind also taking a look at our project we are open to teammate.

**Comment by richard457** [comment]
@ShaswatJBabhulgaonkar Would you mind also taking a look at our project we are open to teammate.

**Comment by harlikshah** [comment]
Hi @atearjen ,
I am currently pursuing my Masters in Computer Science in California and have 2 years of work experience as a Software Developer at top MNC where I had build their applications from scratch and I am interested in mobile application too. Let me know if you are looking for a teammate.
Regards,
Harlik Shah
shahharlik@csu.fullerton.edu

**Comment by chaigoyal** [comment]
Hey! I'm an EECS and Business (MET) student at UC Berkeley (www.linkedin.com/in/chaigoyal). I can join and work on much of the non-technical work (and of course help with technical as demand dictates). Let me know if any of you want to team up.

**Comment by atearjen** [comment]
Hello all, thank you so much for your interest. Our team is very serious about our product and we are a group that has been working together for some time to develop our idea and recently decided to look for funding. After careful consideration, we have decided that we will not take on a fourth member at this time. Thank you so much for reaching out and I hope you all find awesome projects to work for!
