### ISSUE TITLE
*CS Student Here* - [LOOKING FOR TEAM]

### ISSUE THREAD

**Issue by henchik** [fix-the-internet/spring-mvp-lab#75]
** Name **
Chen Stanilovsky
** Skillset **
C++, JS, Data Processing, Python
** Short Bio **
Hey everyone, I am a first year CS student who is currently taking Discrete maths and Matrix algebra. Before this semester, I have taken Calculus 2 and various software development courses. I am looking to apply my knowledge and learn something new.
** Why Work With Me **
I am super passionate about coding and therefore I love learning. I am willing to pick up on various technologies, languages, and libraries to work on your project. Also, I have recently won "Best Data Science Hack" in Hack Brooklyn's virtual hackathon. You can see the post on my linkedin, linked below.
** Location **
Brooklyn, Ny
** University / Work Affiliation **
Uni: CUNY Hunter College
Work: Blue Studios (STEM Education Start-Up)
** LinkedIn **
https://www.linkedin.com/in/chen-stanilovsky/

**Comment by erangell** [comment]
If you can't find a project on this site, would exploring the following technologies interest you?

Python Speech To Text Converter: https://codeloop.org/python-speech-recognition-with-google-speech

KALDI: good recognition engine which can run on Android if model is small enough to fit
http://kaldi-asr.org/doc/index.html
https://github.com/alphacep/kaldi-android-demo

VOSK: for building a server-based speech recognition system with large models
https://alphacephei.com/en/#opensource

**Comment by henchik** [comment]
Thanks for your reply, I would be interested in this:

> Python Speech To Text Converter: https://codeloop.org/python-speech-recognition-with-google-speech

**Comment by erangell** [comment]
Thanks Chen.  It may be too late to add a project for this Mozilla grant, but I'll have my friend who lives in Brooklyn contact you via email.  I saw it on your online resume.

**Comment by erangell** [comment]
For anyone else who may see this, the project we are working on is decentralized speech transcription for communities where privacy and ownership of their data is a big concern.  They don't want any service that can use their data for marketing or user profiling.

**Comment by henchik** [comment]
Sure please tell them to contact me at: chen.stanilovsky92@myhunter.cuny.edu
