### ISSUE TITLE
Meeting new people in small groups instead of 1-1 dating apps

### ISSUE THREAD

**Issue by swijckmans** [fix-the-internet/spring-mvp-lab#79]
We're building a platform to hangout in small groups with others (4-5) people.

The idea started around new year when me and my co founder both were spending time abroad and found that it's is still very hard to meet new people in real life today. Tinder is dating, bumble says it isn't but only does 1-1. We just want to hangout with like minded people and go from there.

So the way we are tackling this problem is by making it dead simple to host a hangout. If you don't know the details doesn't matter you can make a poll... Stuff like: roadtrip to [cool place], Surfing anyone?, Hangout at the mall...

Any thoughts?

Check out our website comoon.app

**Comment by nanayaw25** [comment]
Hey! I just checked out your website and I actually have had a similar idea for awhile that I have wanted to develop. I would love to chat some more about a potential collaboration or partnership if you're interested. My email is nana.boakye.jr25@gmail.com.

**Comment by swijckmans** [comment]
Hi,Thanks for reaching out.Sounds cool, can you tell me a little more about yourself?SimonOn Apr 17, 2020 21:32, nanayaw25 <notifications@github.com> wrote:
Hey! I just checked out your website and I actually have had a similar idea for awhile that I have wanted to develop. I would love to chat some more about a potential collaboration or partnership if you're interested. My email is nana.boakye.jr25@gmail.com.

**Comment by nanayaw25** [comment]
What do you want to know? Briefly: I am a Data Analyst. I have been coming
up with ideas for awhile now and have been gradually developing them.

**Comment by swijckmans** [comment]
Hi,That's cool!Could you tell me a little more about your interests, how you came to the idea,what your background is, can you code and if so what language, perhaps even where you are from...A little more about us.Comoon is currently being run by me and Tobias. Tobias has been coding for a while, he is currently studying computer science and mastering in Machine Learning. He is in charge of the development and we are building the platform on react native.I have a background in solution engineering, I'm Ex-Microsoft and am mainly driving the business end of things. Both of us were spending time abroad and started talking about how messed up online dating is and how hard it is to just meet new friends when you are new to an area.We're both Belgian but live a little all over the place. Tobias is currently in Portugal and I am living between London and Mechelen.If you have any questions please don't hesitate to ask!SimonOn Apr 17, 2020 21:44, nanayaw25 <notifications@github.com> wrote:

What do you want to know? Briefly: I am a Data Analyst. I have been coming

up with ideas for awhile now and have been gradually developing them.



On Fri, Apr 17, 2020 at 3:35 PM SimonWijckmans <notifications@github.com>

wrote:



> Hi,Thanks for reaching out.Sounds cool, can you tell me a little more

> about yourself?SimonOn Apr 17, 2020 21:32, nanayaw25 <
